services:
  db:
    image: postgres:16
    environment: 
      POSTGRES_DB: medodsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123"
    ports:
      - "5434:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./dbInit/dbInit.sql:/docker-entrypoint-initdb.d/init.sql
  tokens:
    build:
      dockerfile: services/tokens/Dockerfile
      context: .
    ports:
      - "8082:8082"
    depends_on:
      - db